CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_SCD4X=y

CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_CHARACTER_FRAMEBUFFER=y

CONFIG_SHELL=y
CONFIG_SHELL_STACK_SIZE=4096

# Settings and Persistent Storage
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_SENSOR_SHELL=y
CONFIG_LOG=y

CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_EVENTS=y

# Bluetooth support (Stable config from weactc6)
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="SCD41_Monitor"
CONFIG_BT_DEVICE_APPEARANCE=833
CONFIG_BT_SMP=y
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_L2CAP_TX_BUF_COUNT=10
CONFIG_BT_BUF_ACL_TX_COUNT=10
CONFIG_BT_ATT_PREPARE_COUNT=5
CONFIG_BT_RX_STACK_SIZE=2200

# GPIO for possible reset if needed
CONFIG_GPIO=y
